name: Maven Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: |
          8
          11
        cache: maven

    # Build production code only because test code uses HTTP client since JDK 11
    - name: Build
      env:
        JAVA_HOME: ${{ env.JAVA_HOME_8_X64 }}
      run: mvn clean package -Dmaven.test.skip=true

    - name: Test
      env:
        JAVA_HOME: ${{ env.JAVA_HOME_11_X64 }}
      run: mvn test
